version: '3.4'

services:
  ddd.webapi:
    image: ${DOCKER_REGISTRY-}dddwebapi
    build:
      context: .
      dockerfile: DDD.WebApi/Dockerfile
    networks:
      - mynet
  mongo:
    image: mongo:latest
    restart: always
    container_name: debug-mongo
    hostname: host-mongo
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./data/:/data/db
      - ./data/log:/var/log/mongodb/
    ports:
      - "27017:27017"
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
volumes:
  mongo:
    driver: local